/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 1;
  /** RegularExpression Id. */
  int FUNCTION_NAME = 2;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 3;
  /** RegularExpression Id. */
  int LBRACE = 4;
  /** RegularExpression Id. */
  int RBRACE = 5;
  /** RegularExpression Id. */
  int SEMICOLON = 6;
  /** RegularExpression Id. */
  int SPACE = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"DEF\"",
    "<FUNCTION_NAME>",
    "<PARAMETER_NAME>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\" \"",
    "\"+\"",
    "\"*\"",
    "<token of kind 10>",
    "\"\\t\"",
    "\"\\n\"",
  };

}
