PARSER_BEGIN(SyntaxChecker)

public class SyntaxChecker {
    public static void main(String[] args) throws ParseException {
        try {
            new SyntaxChecker(System.in).parse();
            System.out.println("PASS");
        } catch (Throwable e) {
            // Catching Throwable is ugly but JavaCC throws Error objects!
            System.out.println("FAIL" + e.getMessage());
        }
    }
}

PARSER_END(SyntaxChecker)

SKIP:  { "\t" | "\r" }
TOKEN:
{
  "("
| ")"
| "+"
| "*"
| <NUM: (["0"-"9"])+>
| <DEF: "DEF">
| <MAIN: "MAIN">
| <FUNCTION_NAME: (["A"-"Z"])+>
| <PARAMETER_NAME: (["a"-"z"])+>
| <LBRACE: "{">
| <RBRACE: "}">
| <SPACE: " ">
| <SEMICOLON: ";">
| <EOL: "\n">
| <DEFINE: <DEF> <SPACE>>
}

void parse():
{
}
{
    // File ends with EOF
    start() <EOF>
}

void start() throws ParseException:
{
}
{
    (
        // Declaring either a MAIN function or a normal (non-MAIN) function
        //<DEFINE> (normal_function() | main_function() | <DEFINE> normal_function())
        <DEFINE> (<FUNCTION_NAME> <SPACE> normal_function() | <DEFINE> normal_function() | main_function())

        // Each line must end with EOL
        try {
            <EOL>
        }

        // If a line didn't end with EOL, alert the user and quit
        catch (ParseException e) {
            System.err.println("[LEXING ERROR] Invalid line terminator.");
            throw e;
            System.exit(0);
        }
    )* // Any number of normal functions is permitted

}

//void normal_function(): {} { (<DEF>" "<FUNCTION_NAME>" "<PARAMETER_NAME>" "<LBRACE>" "E()" "<RBRACE>" "";"<EOL>)* <EOF> }
// Recognises function declarations
void normal_function() throws ParseException:
{
}
{
    try {
        (
        //<FUNCTION_NAME>
        //" "
        <PARAMETER_NAME>
        " "
        <LBRACE>
        " "
        E()
        " "
        <RBRACE>
        " "
        <SEMICOLON>
        )
    }

    catch (ParseException e) {
        System.err.println("[PARSING ERROR] Incorrect declaration.");
        throw e;
        System.exit(0);
    }
}

void main_function():
{
}
{
    (
    <MAIN>
    <SPACE>
    <LBRACE>
    <SPACE>
    E()
    <SPACE>
    <RBRACE>
    <SPACE>
    <SEMICOLON>
    )
}
/*
void main_function() throws ParseException:
{
}
{
    try {
        (<DEF>" ""MAIN"" "<LBRACE>" "E()" "<RBRACE>" "<SEMICOLON>)
    }

    catch (ParseException e) {
        System.err.println("[PARSING ERROR] Incorrect declaration of MAIN.");
        System.exit(0);
    }
}
*/
void E(): {} { T() ("+" T())*      }
void T(): {} { F() ("*" F())*      }
// Recognises function calls
void function_call() throws ParseException:
{
}
{
    // Function calls within the function body should be of the type function_name(function_parameters)
    try {
        <FUNCTION_NAME>"(" E() ")"
    }

    catch (ParseException e) {
        System.err.println("[PARSING ERROR] Incorrect function call.");
        throw e;
        System.exit(0);
    }
}
void F() throws ParseException:
{
}
{
    try {
        (<NUM> | <PARAMETER_NAME> | function_call())
    }

    catch (ParseException e) {
        System.err.println("[PARSING ERROR] Expected a numerical value, a parameter or a function call.");
        throw e;
        System.exit(0);
    }
}