/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int DEF = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int FUNCTION_NAME = 10;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int EOL = 16;
  /** RegularExpression Id. */
  int DEFINE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "<NUM>",
    "\"DEF\"",
    "\"MAIN\"",
    "<FUNCTION_NAME>",
    "<PARAMETER_NAME>",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\";\"",
    "\"\\n\"",
    "<DEFINE>",
  };

}
